name: Run tests
on:
    pull_request:
    push:
        branches:
            - master
            - dev

jobs:
    tests:
        name: PHP ${{ matrix.php }} with Guzzle ${{ matrix.guzzle }}
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php: [ 7.1, 7.2, 7.3, 7.4, 8.0 ]
                guzzle: [ ^6, ^7 ]
                exclude:
                    -   php: 7.1
                        guzzle: ^7

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: json,curl

            -   name: Install dependencies
                run: composer require guzzlehttp/guzzle:${{ matrix.guzzle }} --no-interaction --prefer-dist

            -   name: Run test suite
                run: ./vendor/bin/phpunit --testdox --verbose

    coverage:
        name: Coverage
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    coverage: pcov
                    php-version: 8.0

            -   name: Install dependencies
                run: composer require laravel/lumen:"^8" --no-interaction --prefer-dist

            -   name: Run tests for coverage
                run: ./vendor/bin/phpunit --coverage-clover=coverage.xml

            -   name: Push to Codecov
                run: bash <(curl -s https://codecov.io/bash)
                env:
                    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
